version: 2
sources:
  - name: shopify
    database: trans-radius-363407

    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: updated_at

    schema: staging_fivetran_shopify
    tables:
      - name: order
      - name: customer
      - name: order_discount_code
      - name: order_tag
      - name: order_note_attribute
      - name: order_line


      
  - name: recharge
    database: trans-radius-363407

    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: updated_at

    schema: staging_fivetran_recharge
    tables:
      - name: order
      - name: customer
        columns:
            - name: id
              description: Primary key of the recharge customer table
              tests:
                - unique
                - not_null
            - name: external_customer_id_ecommerce
              description:  key of the shopify customer table, sometimes Null Values, sometimes multiples Recharge customer ñaping to same shopify customer and sometimes recharge customer mapping to a non existing Shopify Customer.
      - name: subscription
      - name : order_line_item

    
  - name: BIContent900
    database: trans-radius-363407

    freshness: # default freshness
      warn_after: {count: 72, period: hour}
      error_after: {count: 120, period: hour}
    loaded_at_field: _airbyte_extracted_at

    schema: staging_airbyte_cloud
    tables:
      - name: content900_invalidOrder_customerIds
      - name: content900_invalidOrder_orderNames
      - name: content900_invalidOrder_testDiscountCodes
      - name: content900_mapping_Grapevine_acquisitionChannel
      - name: content900_mapping_orderDiscountCode_acquisitionChannel 
      - name : content900_Product


  - name: externalData
    database: trans-radius-363407

    freshness: # default freshness
      warn_after: {count: 240, period: hour}
      error_after: {count: 480, period: hour}
    loaded_at_field: _airbyte_extracted_at

    schema: staging_airbyte_cloud
    tables:
      - name: externalData_Grapevine_Survey_Data

