version: 2
sources:
  - name:  snapshot
    database:  trans-radius-363407
    schema: dbt_snapshots
    tables:
      - name: subscription_snapshot_check

  - name:  ga4_raw
    database:  trans-radius-363407
    schema: analytics_309612605
    tables:
      - name: full_events

  - name: shopify
    database: trans-radius-363407

    loaded_at_field: updated_at

    schema: staging_fivetran_shopify
    tables:
      - name: order
        freshness: 
          warn_after: { count: 24, period: hour }
          error_after: { count: 48, period: hour }
        loaded_at_field: created_at
      - name: customer
      - name: customer_address
      - name: order_discount_code
      - name: order_tag
      - name: order_note_attribute
      - name: order_line
      - name: order_line_refund
      - name: refund
      
      
      - name: order_shipping_line
      - name: transaction #for Refund amounts

  - name: recharge_airbyte
    database: trans-radius-363407

    loaded_at_field: updated_at

    schema: staging_airbyte_cloud
    tables: 
      - name: recharge_customers
      - name: recharge_subscriptions
      - name: recharge_orders
        freshness: 
          warn_after: { count: 24, period: hour }
          error_after: { count: 48, period: hour }
        loaded_at_field: _airbyte_extracted_at
      - name: recharge_addresses
      - name: recharge2_charges

  - name: recharge_fivetran
    database: trans-radius-363407

    loaded_at_field: updated_at

    # schema: staging_fivetran_recharge
    # tables:
    #   - name: order

    #   - name: customer
    #     columns:
    #       - name: id
    #         description: Primary key of the recharge customer table
    #         data_tests:
    #           - unique
    #           - not_null
    #       - name: external_customer_id_ecommerce
    #         description: key of the shopify customer table, sometimes Null Values, sometimes multiples Recharge customer mapping to same shopify customer and sometimes recharge customer mapping to a non existing Shopify Customer.
    #   - name: subscription
    #   - name: order_line_item
    #   - name: address

  - name: airtable
    database: trans-radius-363407

    freshness: 
      warn_after: { count: 24, period: hour }
      error_after: { count: 48, period: hour }
    loaded_at_field: _airbyte_extracted_at

    schema: staging_airbyte_cloud
    tables:
      - name: airtable_airupsell___basefullupsells_tblRQj1DtQsrDcWef
        columns:
          - name: upsell_subscription_id_recharge
            description: id of the gift Subscription in Upsell
            data_tests: #updated to data_data_tests for dbt 1.8
              - not_null
              - unique

  - name: BIContent900
    database: trans-radius-363407

    schema: staging_airbyte_cloud
    tables:
      - name: content900_Acquisition_Channel
        columns:
          - name: acquisition_channel
            description: Primary key
            data_tests:
              - unique
              - not_null
      - name: content900_Product_Category
        columns:
          - name: category
            description: Primary key of the product category
            data_tests:
              - unique
              - not_null
      - name: content900_Product_Variant
        freshness: 
          warn_after: { count: 24, period: hour }
          error_after: { count: 120, period: hour }
        loaded_at_field: _airbyte_extracted_at
        columns:
          - name: sku
            description: Primary key of the product variants
            data_tests:
              - unique
              - not_null
          - name: quantity_refill
            description: Number of Refills in the Product Variant 
            data_tests:
              - not_null
          - name: Category
            data_tests:
              - relationships:                  
                  to: source('BIContent900', 'content900_Product_Category')
                  field: category
      - name: content900_invalidOrder_customerIds
        columns:
          - name: customerId
            description: Primary key
            data_tests:
              - unique
              - not_null
      - name: content900_invalidOrder_orderNames
      - name: content900_invalidOrder_testDiscountCodes
        columns:
          - name: DiscountCode
            description: Primary key
            data_tests:
              - unique
              - not_null
      - name: content900_mapping_Grapevine_acquisitionChannel
        columns:
          - name: howHeard
            description: Primary key
            data_tests:
              - unique
              - not_null
          - name: acquisitionChannel
            data_tests:
              - relationships:
                  #to: ref('content900_Acquisition_Channel')
                  to: source('BIContent900', 'content900_Acquisition_Channel')
                  field: acquisition_channel
      - name: content900_mapping_orderDiscountCode_acquisitionChannel
        columns:
          - name: code
            description: Primary key
            data_tests:
              - unique
              - not_null
          - name: acquisitionChannel
            data_tests:
              - relationships:
                  to: source('BIContent900', 'content900_Acquisition_Channel')
                  field: acquisition_channel

      - name: content900_tests_customer_cohort_groups
      - name: content900_Region
        columns:
          - name: Name
            description: Primary key of Region
            data_tests:
              - unique
              - not_null
      - name: content900_Country
        columns:
          - name: Name
            description: Primary key of Countries
            data_tests:
              - unique
              - not_null
          - name: Region
            description: Region of the country (900 defined regions)
            data_tests:
              - relationships:                  
                  to: source('BIContent900', 'content900_Region')
                  field: name
      - name: content900_Campaign_Location
        columns:
          - name: Spark_campaign_location
            description: Primary key of campaign location
            data_tests:
              - unique
              - not_null

      - name: content900_CostLogistics 
        data_tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - region
                - clientType
                - year
                - month
        columns:
          - name: region
            data_tests:
              - relationships:                  
                  to: source('BIContent900', 'content900_Region')
                  field: name
      - name: content900_CostProduction
        columns:
           - name: productCategory
             data_tests:
              - relationships:                  
                  to: source('BIContent900', 'content900_Product_Category')
                  field: category
           - name: productType
             data_tests:
              - accepted_values:
                  values: ['Refill','Reusable case']
      
  - name: externalDataAirbyte
    database: trans-radius-363407

    schema: staging_airbyte_cloud
    tables:
      - name: externalData_Grapevine_Survey_Data
        columns:
          - name: order_id
            description: One acquisition per order
            data_tests:
              - not_null
      - name: recharge_okr_CumSubscriptionsWeekly
        columns:
          - name: weekstart
            description: Primary key
            data_tests:
              - unique
              - not_null
      - name: sparkDo__900CARE__PLATFORM_DAILY_SPEND
        freshness: 
          warn_after: { count: 24, period: hour }
          error_after: { count: 48, period: hour }
        loaded_at_field: _airbyte_extracted_at
      - name: ga4_demographic_country_report
        freshness: 
          warn_after: { count: 24, period: hour }
          error_after: { count: 48, period: hour }
        loaded_at_field: _airbyte_extracted_at
        columns:
          - name: date || country
            description: Primary key
            data_tests:
              - unique
              - not_null

  - name: externalDataFivetran
    database: trans-radius-363407
    schema: staging_fivetran_drive
    tables:
      - name: yotpo

  - name: retently
    database: trans-radius-363407

    freshness: 
      warn_after: { count: 24, period: hour }
      error_after: { count: 48, period: hour }
    loaded_at_field: _airbyte_extracted_at

    schema: staging_airbyte_cloud
    tables:
      - name: retently_feedback

  - name: reviewsio
    database: trans-radius-363407
    schema: staging_fivetran_reviewsio
    tables:
      - name: review_and_question
      - name: review_attribute
      - name: company_review_invitation
